[planet]
name           = "K2-18 b"       # look up mass/radius/Teq in packaged data
FXUV_erg_cm2_s = "from_data"     # incident XUV (energy flux), or stellar irradiance at the planet’s orbit

[composition]                    # mass fractions (sum≈1); auto-normalized if enabled below
H2  = 0.90
H2O = 0.10
O2  = 0.0
CO2 = 0.0
CO  = 0.0
CH4 = 0.0
N2  = 0.0
NH3 = 0.0
H2S = 0.0
SO2 = 0.0
S2  = 0.0

[physics]
efficiency = 0.30                 # mass loss efficiency eta (η), dimensionless
albedo     = 0.30
beta       = 0.75                 # dayside redistribution factor, 0.5<b<1
emissivity = 1.0

[xuv.sigma_cm2]                   # atomic cross-sections sigma (σ) (cm^2) for the dissociated outflow
H = 1.89e-18
O = 2.00e-18
C = 2.50e-18
N = 3.00e-18
S = 6.00e-18

[infrared.kappa_cm2_g]            # IR mass opacities kappa (κ) (cm^2 g^-1) for the bolometric region
H2  = 1.0e-2
H2O = 1.0
O2  = 1.0
CO2 = 1.0
CO  = 1.0
CH4 = 1.0
N2  = 1.0
NH3 = 1.0
H2S = 1.0
SO2 = 1.0
S2  = 1.0

[diffusion.b]                     # b_ij(T) = A * T^gamma (cm^-1 s^-1); keys can be "HO" or "H-O"
HO = { A=4.8e17, gamma=0.75 }
HC = { A=6.5e17, gamma=0.70 }
HN = { A=5.0e17, gamma=0.73 }
HS = { A=5.8e17, gamma=0.70 }
OC = { A=8.6e16, gamma=0.76 }
ON = { A=9.0e16, gamma=0.78 }
OS = { A=8.5e16, gamma=0.78 }
CN = { A=7.5e16, gamma=0.74 }
CS = { A=7.2e16, gamma=0.74 }
NS = { A=8.0e16, gamma=0.76 }

[fractionation]
allow_dynamic_light_major = true  # let the code pick the "light major species" automatically
forced_light_major        = "H"   # used only if the above is false
tol                       = 1e-5
max_iter                  = 100

[advanced]                        # optional overrides
auto_normalize_X = true           # normalize composition if sum!=1