[planet]
name           = "my_planet"     # look up mass(grams)/radius(cm)/Teq(K) in packaged data (planet_params.json)
FXUV_erg_cm2_s = "from_data"     # "from_data" to read .json value, or input value. Incident XUV (energy flux), or stellar irradiance at the planet’s orbit, ergs cm-2 s-1

[composition]                    # atmospheric mass fractions (sum≈1); auto-normalized if enabled below
H2  = 0.9
H2O = 0.1
O2  = 0
CO2 = 0
CO  = 0
CH4 = 0
N2  = 0
NH3 = 0
H2S = 0
SO2 = 0
S2  = 0

[physics]
efficiency = 0.30                 # mass loss efficiency eta (η), dimensionless
albedo     = 0.30
beta       = 0.75                 # dayside redistribution factor, 0.5<b<1
emissivity = 1.0

[xuv.sigma_cm2]                   # atomic cross-sections sigma (σ) (cm^2) for the dissociated outflow at ~20 eV assuming neutral atoms (Verner+1996)
H = 1.89e-18
O = 1.09e-17
C = 1.01e-17
N = 1.41e-17
S = 3.27e-17

[infrared.kappa_cm2_g]            # IR mass opacities kappa (κ) (cm^2 g^-1) for the bolometric region
H2  = 1e-2
H2O = 1.0                         # IR (1–30 µm) Planck-mean-ish at ~1000 K, ~1 bar
O2  = 2e-2                        # weak in thermal IR except CIA/quadrupole effects
CO2 = 5e-1                        # moderate to strong in thermal IR
CO  = 1e-1                        # weaker as a band-limited mean
CH4 = 5e-1                        # moderate to strong in thermal IR
N2  = 1e-2                        # weak in thermal IR except CIA/quadrupole effects
NH3 = 5e-1                        # moderate to strong in thermal IR
H2S = 8e-1                        # moderate to strong in thermal IR
SO2 = 1.0                         # strong in thermal IR
S2  = 2e-1                        # probably low to moderate

[diffusion.b]                     # b_ij(T) = A * T^gamma (cm^-1 s^-1); keys can be "HO" or "H-O"
HO = { A=4.8e17, gamma=0.75 }     # Zahnle and Kasting 1986, O loss with background H
HC = { A=1.577e18, gamma=0.5 }    # Banks+Kockarts 1973 fits
HS = { A=1.539e18, gamma=0.5 }    # Banks+Kockarts 1973 fits
HN = { A=1.569e18, gamma=0.5 }    # Banks+Kockarts 1973 fits
OC = { A=5.807e17, gamma=0.5 }    # Banks+Kockarts 1973 fits
ON = { A=5.566e17, gamma=0.5 }    # Banks+Kockarts 1973 fits
OS = { A=4.656e17, gamma=0.5 }    # Banks+Kockarts 1973 fits
CN = { A=5.981e17, gamma=0.5 }    # Banks+Kockarts 1973 fits
CS = { A=5.146e17, gamma=0.5 }    # Banks+Kockarts 1973 fits
NS = { A=4.872e17, gamma=0.5 }    # Banks+Kockarts 1973 fits

[fractionation]
allow_dynamic_light_major = true  # let the code pick the "light major species" automatically
forced_light_major        = "H"   # used only if the above is false
tol                       = 1e-5
max_iter                  = 100

[advanced]                        # optional overrides
auto_normalize_X = true           # normalize composition if sum!=1